using FileAnalysisService.Presentation.Handlers.GetReportBySubmissionId;

namespace FileAnalysisService.Presentation.Handlers.GetReportsByTaskId;

public record GetReportsByTaskIdResponse(IEnumerable<GetReportResponse> Reports);